name: Deno Deploy Preview

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2

      - name: Set Deno Deploy project name
        id: project_name
        run: |
          echo "name=$(echo '${{ github.event.repository.name }}' | tr '.' '-')" >> $GITHUB_OUTPUT

      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: ${{ steps.project_name.outputs.name }}
          entrypoint: deno/artifact-proxy.ts
