name: Deno Deploy

on:
  push:
    # branches:
      # - development

jobs:
  deploy:
    name: Deploy to Deno Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: "1.2.0"

      - name: Cache Bun dependencies
        uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('bun.lockb') }}
          restore-keys: ${{ runner.os }}-bun-

      - name: Build UI
        run: bun run tools/build.ts

      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "xp-ubq-fi"
          entrypoint: "deno/artifact-proxy.ts"
        env:
          DENO_DEPLOY_TOKEN: ${{ secrets.DENO_DEPLOY_TOKEN }}
